[[patch.replace]]
original    = "UI_Loading.ChaletComprime-CologneEighty"
replacement = "MyFont"

[[patch.replace]]
original    = "UI_Loading.ChaletComprime-CologneEighty_PageA"
replacement = "MyFont.MyFont_PageA"
