[mod]
name        = "FontTest"
version     = "0.1"
author      = "deadYokai"
description = "Example mod, that replaces original font"

[[patch]]
dir = "Fonts"
package = "UI_Loading_SF_LOC_INT"

[[patch.replace]]
original = "UI_Loading:Emerge_BF"
modfile = "MyFont"

[[patch.replace]]
original = "UI_Loading:Emerge_BF.Emerge_BF_PageA"
modfile  = "MyFont_PageA"

# Add one [[patch]] block per UPK you want to replace exports in.
# Then run:
#   ue3-tools mod extract <Pkg.upk> <ExportName> . --dir <subdir>
# to populate the blob files.

# [[patch]]
# dir     = "Fonts"
# package = "UI_Loading"
#
#   [[patch.replace]]
#   original = "Emerge_BF"
#   modfile  = "MyHudFont"
